
(SYMBOL-NAME (QUOTE XYZ))
"XYZ"

(PROGN (SETQ *GENSYM-COUNTER* 32) (gensym) (PRIN1-TO-STRING (GENSYM "FOO-")))
"#:FOO-33"

(PROGN (SETQ *GENSYM-COUNTER* 32) (gensym) (PRIN1-TO-STRING (GENSYM "garbage-")))
#+XCL "#:|garbage|-33"
#+(or CLISP ECL AKCL ALLEGRO) "#:|garbage-33|"
#-(or XCL CLISP AKCL ALLEGRO) UNKNOWN

