#!/bin/sh
THIS_DIR=`pwd`
SHARED_CONFIG_FLAGS="--without-profile \
 --without-cmp \
 --without-asdf \
 --without-defsystem \
 --enable-debug \
 --disable-shared \
 --without-serve-event \
 --with-tcp \
 --without-rt \
 --enable-threads \
 --without-gmp"

echo "=================================================="
echo "Making the build-platform ECL to be used for cross compilation:"
echo "=================================================="
make distclean
DEVROOT=/Developer/Platforms/iPhoneSimulator.platform/Developer
./configure  $SHARED_CONFIG_FLAGS \
 --prefix=$THIS_DIR/install_iPhoneSimulator/ \
 CC="$DEVROOT/usr/bin/gcc" \
 AR=$DEVROOT/usr/bin/ar \
 RANLIB=$DEVROOT/usr/bin/ranlib \
 NM=$DEVROOT/usr/bin/nm \
 CPP=$DEVROOT/usr/bin/cpp \
 ac_cv_path_NM=$DEVROOT/usr/bin/nm \
 dynamic_ffi=no

make
make install
chmod -R 775 ./install_iPhoneSimulator/lib/

echo "=================================================="
echo "Making the host-platform ECL to be used on the iPhone:"
echo "=================================================="
make distclean
mkdir build
cp cross_config_iPhoneOS build/cross_config
echo "ECL_TO_RUN=$THIS_DIR/install_iPhoneSimulator/bin/ecl" >> build/cross_config

DEVROOT=/Developer/Platforms/iPhoneOS.platform/Developer
sh ./configure  $SHARED_CONFIG_FLAGS \
 --prefix=$THIS_DIR/install_iPhoneOS/ \
 --host=arm-apple-darwin \
 --target=arm-apple \
 CC="$DEVROOT/usr/bin/gcc-4.0 -arch armv6" \
 AR=$DEVROOT/usr/bin/ar \
 RANLIB=$DEVROOT/usr/bin/ranlib \
 NM=$DEVROOT/usr/bin/nm \
 CFLAGS="-arch armv6 -pipe -std=c99 -Wno-trigraphs -fpascal-strings -fasm-blocks -O0 -Wreturn-type -Wunused-variable -fmessage-length=0 -fvisibility=hidden -miphoneos-version-min=2.0 -gdwarf-2 -miphoneos-version-min=2.0 -I/Library/iPhone/include -isysroot $DEVROOT/SDKs/iPhoneOS2.0.sdk" \
 LDFLAGS="-arch armv6 -pipe -std=c99 -gdwarf-2 -I/Library/iPhone/include -isysroot $DEVROOT/SDKs/iPhoneOS2.0.sdk" \
 CPP=$DEVROOT/usr/bin/cpp \
 ac_cv_path_NM=$DEVROOT/usr/bin/nm \
 ac_cv_func_setpgrp_void=yes \
 LIBPOSTFIX=_iPhoneOS \
 dynamic_ffi=no

make
make install
echo "Renaming library files"
cp install_iPhoneOS/lib/libecl.a install_iPhoneOS/lib/libecl_iPhoneOS.a && cp install_iPhoneOS/lib/libeclgc.a install_iPhoneOS/lib/libeclgc_iPhoneOS.a
echo "=================================================="
echo "Finished compiling!  Inspect the output for errors"
echo "=================================================="

