#!/bin/sh

usage()
{
  cat <<EOF
Usage: eclconfig [OPTIONS] [LIBS]
Options: 
	[--cflags]
	[--libs|--ldflags]
Libs:
	cmp
EOF
}

LDFLAGS="-lecl"
for i in $*; do
  case $i in
    --cflags|-c)
      echo_cflags=yes
      ;;
    --libs|--ldflags|-l)
      echo_ldflags=yes
      ;;
    cmp)
      LDFLAGS="$LDFLAGS -lcmp"
      ;;
    *)
      usage 1 >&2
      ;;
    esac;
done

if test "$echo_cflags" = "yes"; then
  echo "@ECL_CFLAGS@ -I@includedir\@"
fi

if test "$echo_ldflags" = "yes"; then
  echo "@LDRPATH@ -L@libdir\@ $LDFLAGS @LDFLAGS@ @CLIBS@"
fi
