#!/bin/sh
./configure \
 --prefix=/Users/red/lib/iphoneos-ecl/ \
 --host=arm-apple-darwin \
 --with-cross-host=arm-apple-darwin \
 --target=arm-apple \
 --disable-shared \
 CC=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.0 \
 NM=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/nm \
 AR=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/ar \
 RANLIB=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/ranlib \
 CFLAGS="-arch armv6 -pipe -std=c99 -Wno-trigraphs -fpascal-strings -fasm-blocks -O0 -Wreturn-type -Wunused-variable -fmessage-length=0 -fvisibility=hidden -miphoneos-version-min=2.0 -gdwarf-2 -mthumb -miphoneos-version-min=2.0 -I/Library/iPhone/include -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS2.0.sdk" \
 LDFLAGS="-arch armv6 -pipe -std=c99 -gdwarf-2 -mthumb -I/Library/iPhone/include -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS2.0.sdk" \
 CPP=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/cpp \
 ac_cv_path_NM=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/nm \
 ac_cv_func_setpgrp_void=yes
